- hosts: localhost
  become: yes
  vars:
    - fedora_version: 36

  tasks:
    - name: Update system packages.
      dnf:
        name: '*'
        state: latest

    - name: Install system packages.
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:  # Chrome, Firefox...
          - dnf-plugins-core
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
          - gnome-tweaks
          - gnome-extensions-app
          - snapd
          - vlc
          - transmission
          - geary
          - chromium

    # Using shell command as workaround because there is no Ansible plugin for dnf config-manageer.
    # https://github.com/ansible/ansible/issues/46963
    - name: Add Docker remote repository to dnf.
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Create symlink to support snap classic.  # Needed to install VS Code.
      command: ln -sf /var/lib/snapd/snap /snap

    - name: Install VS Code.
      community.general.snap:
        name:
          - code
        classic: true

    - name: Install Postman.
      community.general.snap:
        name:
          - postman

    - name: Install Docker.
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
