- hosts: localhost
  vars:
    - fedora_version: 37
    - user: ethan
    - user_name: Ethan Meanor
    - user_email: ethan@meanor.ca

  tasks:
    - name: Remove clutter.
      become: yes
      dnf:
        name: "{{ packages }}"
        state: removed
      vars:
        packages:
          - cheese
          - libreoffice-calc
          - libreoffice-impress
          - gnome-contacts
          - gnome-maps
          - gnome-photos
          - gnome-tour
          - gnome-weather
          - simple-scan
          - totem

    - name: Update system packages.
      become: yes
      dnf:
        name: '*'
        state: latest

    - name: Enable RPM Fusion repository.
      become: yes
      dnf:
        name: "{{ downloads }}"
        state: latest
        disable_gpg_check: True
      vars:
        downloads: 
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm

    - name: Install system packages.
      become: yes
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - dnf-plugins-core
          - python3-pip
          - gnome-tweaks
          - snapd
          - vlc
          - transmission
          - geary
          - chromium

    - name: Install Python packages.
      ansible.builtin.pip:
        name: "{{ packages }}"
      vars:
        packages:
          - psutil  # Dependency for community.general.dconf.

    # Using shell command as workaround because there is no Ansible plugin for dnf config-manageer.
    # https://github.com/ansible/ansible/issues/46963
    - name: Add Docker remote repository to dnf.
      become: yes
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install Docker.
      become: yes
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Enable snap classic mode.
      become: yes
      shell: |
        ln -sf /var/lib/snapd/snap /snap
        . /home/{{ user }}/.bashrc

    - name: Install VS Code.
      become: yes
      community.general.snap:
        name:
          - code
        classic: true

    - name: Install Postman.
      become: yes
      community.general.snap:
        name:
          - core18
          - postman


    # Git configuration.
    - name: Set name for Git user.
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ user_name }}"

    - name: Set email for Git user.
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ user_email }}"


    # System tweaks.
    - name: Add minimize and maximize buttons to window GUI.
      community.general.dconf:
        key: /org/gnome/desktop/wm/preferences/button-layout
        value: "'appmenu:minimize,maximize,close'"

    - name: Allow system volume above 100%.
      community.general.dconf:
        key: /org/gnome/desktop/sound/allow-volume-above-100-percent
        value: "true"

    - name: Enable Night Light.
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: "true"

    - name: Show weekday on system clock.
      community.general.dconf:
        key: /org/gnome/desktop/interface/clock-show-weekday
        value: "true"
